### ISSUE TITLE
native-lib.cpp does not contain the function getAuthChain and getKeyParams

### ISSUE THREAD

**Issue by AayushTaneja** [Catherine22/SecuritySample#1]
![capture](https://user-images.githubusercontent.com/31048248/41208631-3642e2aa-6d43-11e8-8f4b-98826b87826e.JPG)

**Comment by Catherine22** [comment]
It seems like you used new path. Have you checked the following paths?

1. LOCAL_MODULE and LOCAL_SRC_FILES of Android.mk should be the same as ```System.loadLibrary(your LOCAL_MODULE);``` in JNIHelper you defined. Besides, LOCAL_SRC_FILES connects to where your native files are.
2. Native methods you create in the .cpp file are supposed to be named as "Java_PackageNameOfJNIHelper_JNIHelper_MethodName" like ```Java_com_catherine_securitysample_JNIHelper_getAuthChain```. In this case, there must be a ```public native String[] getAuthChain(String key);``` method in your JNIHelper
3. Check parameters and return values.

**Comment by AayushTaneja** [comment]
the getAuthChain and getKeyParams methods are not present in your native-lib.cpp. Even if i create these methods myself, I dont know what code to write in them. Could you please tell what code goes inside these methods.

Please bear with me, I am new to NDK.

**Comment by Catherine22** [comment]
https://github.com/Catherine22/SecuritySample/tree/master/app/src/main/jni

In Android.mk, I defined 

`LOCAL_SRC_FILES := Config.h`
`LOCAL_SRC_FILES := Config.cpp`

Which means functions and variables are packaged in Config.h and Config.cpp. You could create your own methods or files, don't forget to update the path!

**Comment by AayushTaneja** [comment]
Thanks a lot!
