### ISSUE TITLE
Security of Storing Modulus & Exponent Within C

### ISSUE THREAD

**Issue by StuStirling** [Catherine22/SecuritySample#2]
Hi, thanks for this repository. It has helped my own investigation into this area. I am not that familiar with encryption.

You have the modulus and exponent of the RSA public key stored in the Android project. If someone got hold of that they could decode the keys you've encrypted previously and decrypt them easy enough (which is essentially what you're doing in your java code).

Is this just another level of obfuscation at this point and doesn't really provide any more security?

**Comment by Catherine22** [comment]
Hi,

You do have a point.

That is actually the reason I kept these arguments in native c/c++ code. If you decompile your apk, you would get .so files, all the variables you define through NDK including the modulus and exponent are put together and a bit hard to read since they are consecutive.

However, this solution is outdated, keystore is a better option.

**Comment by StuStirling** [comment]
Thanks for your reply. How would keystore help? The keystore would not know how to decode the encrypted keys unless you have a different idea?

 I think the best we can do is making it more difficult like you have done with the RSA keys, but someone would always have the information they needed to decrypt the data.

**Comment by Catherine22** [comment]
1. How would keystore help?
You could store your secret keys by using keystore

2. Someone would always have the information they needed to decrypt the data
Totally

**Comment by StuStirling** [comment]
1. Still wouldn't help placing these keys in at compile time. The Keystore would help if they were returned from the server at runtime

**Comment by Catherine22** [comment]
I think we don't need to do it. 
Let's say you try to encrypt your RSA keys with another key, how do you keep it safe as well?
